package org.unioeste.ilp.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import org.unioeste.ilp.models.User;
import org.unioeste.ilp.models.Pattern;
import org.unioeste.ilp.models.Experience;
import org.unioeste.ilp.models.Attempt;
import org.unioeste.ilp.models.Sample;

import org.unioeste.ilp.models.UserDao;
import org.unioeste.ilp.models.PatternDao;
import org.unioeste.ilp.models.ExperienceDao;
import org.unioeste.ilp.models.AttemptDao;
import org.unioeste.ilp.models.SampleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig patternDaoConfig;
    private final DaoConfig experienceDaoConfig;
    private final DaoConfig attemptDaoConfig;
    private final DaoConfig sampleDaoConfig;

    private final UserDao userDao;
    private final PatternDao patternDao;
    private final ExperienceDao experienceDao;
    private final AttemptDao attemptDao;
    private final SampleDao sampleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        patternDaoConfig = daoConfigMap.get(PatternDao.class).clone();
        patternDaoConfig.initIdentityScope(type);

        experienceDaoConfig = daoConfigMap.get(ExperienceDao.class).clone();
        experienceDaoConfig.initIdentityScope(type);

        attemptDaoConfig = daoConfigMap.get(AttemptDao.class).clone();
        attemptDaoConfig.initIdentityScope(type);

        sampleDaoConfig = daoConfigMap.get(SampleDao.class).clone();
        sampleDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        patternDao = new PatternDao(patternDaoConfig, this);
        experienceDao = new ExperienceDao(experienceDaoConfig, this);
        attemptDao = new AttemptDao(attemptDaoConfig, this);
        sampleDao = new SampleDao(sampleDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Pattern.class, patternDao);
        registerDao(Experience.class, experienceDao);
        registerDao(Attempt.class, attemptDao);
        registerDao(Sample.class, sampleDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        patternDaoConfig.getIdentityScope().clear();
        experienceDaoConfig.getIdentityScope().clear();
        attemptDaoConfig.getIdentityScope().clear();
        sampleDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PatternDao getPatternDao() {
        return patternDao;
    }

    public ExperienceDao getExperienceDao() {
        return experienceDao;
    }

    public AttemptDao getAttemptDao() {
        return attemptDao;
    }

    public SampleDao getSampleDao() {
        return sampleDao;
    }

}
